# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

geovctrs_cpp_convert <- function(data, ptype) {
    .Call(`_geovctrs_geovctrs_cpp_convert`, data, ptype)
}

geovctrs_cpp_geos_version_runtime <- function() {
    .Call(`_geovctrs_geovctrs_cpp_geos_version_runtime`)
}

geovctrs_cpp_geos_version_build <- function() {
    .Call(`_geovctrs_geovctrs_cpp_geos_version_build`)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_geovctrs_RcppExport_registerCCallable', PACKAGE = 'geovctrs')
})
