# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

geovctrs_cpp_convert <- function(data, ptype) {
    .Call(`_geovctrs_geovctrs_cpp_convert`, data, ptype)
}

pmin2 <- function(x1, x2) {
    .Call(`_geovctrs_pmin2`, x1, x2)
}

pmax2 <- function(x1, x2) {
    .Call(`_geovctrs_pmax2`, x1, x2)
}

geovctrs_cpp_envelope <- function(data, naRm) {
    .Call(`_geovctrs_geovctrs_cpp_envelope`, data, naRm)
}

geovctrs_cpp_has_missing <- function(x) {
    .Call(`_geovctrs_geovctrs_cpp_has_missing`, x)
}

geovctrs_cpp_is_finite <- function(x) {
    .Call(`_geovctrs_geovctrs_cpp_is_finite`, x)
}

geovctrs_cpp_is_empty <- function(data) {
    .Call(`_geovctrs_geovctrs_cpp_is_empty`, data)
}

geovctrs_cpp_parse <- function(data) {
    .Call(`_geovctrs_geovctrs_cpp_parse`, data)
}

geovctrs_cpp_get_srid <- function(x) {
    .Call(`_geovctrs_geovctrs_cpp_get_srid`, x)
}

geovctrs_cpp_set_srid <- function(x, srid) {
    .Call(`_geovctrs_geovctrs_cpp_set_srid`, x, srid)
}

geovctrs_cpp_geom_type_id <- function(x) {
    .Call(`_geovctrs_geovctrs_cpp_geom_type_id`, x)
}

geovctrs_cpp_n_geometries <- function(x) {
    .Call(`_geovctrs_geovctrs_cpp_n_geometries`, x)
}

geovctrs_cpp_n_coordinates <- function(x) {
    .Call(`_geovctrs_geovctrs_cpp_n_coordinates`, x)
}

geovctrs_cpp_coordinate_dimensions <- function(x) {
    .Call(`_geovctrs_geovctrs_cpp_coordinate_dimensions`, x)
}

geovctrs_cpp_first_coordinate <- function(x) {
    .Call(`_geovctrs_geovctrs_cpp_first_coordinate`, x)
}

geovctrs_cpp_geos_version_runtime <- function() {
    .Call(`_geovctrs_geovctrs_cpp_geos_version_runtime`)
}

geovctrs_cpp_geos_version_build <- function() {
    .Call(`_geovctrs_geovctrs_cpp_geos_version_build`)
}

geovctrs_cpp_test_buffer2 <- function(data, ptype) {
    .Call(`_geovctrs_geovctrs_cpp_test_buffer2`, data, ptype)
}

geovctrs_cpp_test_buffer2_bad_provider <- function(data, ptype) {
    .Call(`_geovctrs_geovctrs_cpp_test_buffer2_bad_provider`, data, ptype)
}

geovctrs_cpp_test_buffer2_bad_exporter <- function(data, ptype) {
    .Call(`_geovctrs_geovctrs_cpp_test_buffer2_bad_exporter`, data, ptype)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_geovctrs_RcppExport_registerCCallable', PACKAGE = 'geovctrs')
})
